# Generated by Django 4.1.7 on 2023-04-09 15:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.CharField(max_length=1000, verbose_name='Сообщение')),
            ],
        ),
    ]
