# Generated by Django 4.1.7 on 2023-04-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_customerrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Телефон'),
        ),
    ]
