# Generated by Django 4.1.7 on 2023-04-09 17:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_alter_customerrequest_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон'),
        ),
    ]
